### ISSUE TITLE
mouse-menu功能请求三则：fn回调参数应传入点击事件、`v-menu`应支持否定值以完全禁用菜单、分割线支持hidden或末端隐藏

### ISSUE THREAD

**Issue by zheung** [leon-kfd/howdyjs#12]
#### 1、fn回调参数传入点击事件
建议在参数4中传入HTML原生点击事件  
在进行下载文件、复制数据到粘贴板或打开新窗口等，一些可能被浏览器进行安全检查的操作时，一些库如`clipboard.js`需要手动传入HTML事件才能顺利完成功能。但是当前版本中，`fn回调函数`并没有传递每次点击对应的事件。导致只能使用HTML标准已不推荐的全局event，这既不符合标准，也不方便于长期使用，希望后续版本能传入原生事件。

#### 2、`v-menu`应支持否定值以完全禁用菜单
在使用过程中遇到这样的情况：  
`列表中有两种同结构的数据，A类数据不用触发菜单，而B类数据需要`    
- 按照文档在顶层`props`（parasm同级）传入`disabled`项的函数，无效，vue3警告：
`Extraneous non-props attributes (disabled) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. `
- 而后尝试通过往`v-menu`指令传入否定值（`false`、`null`、`undefined`）等，代码均将传入值视为正常的`Object`进行使用，导致各种报错，渲染中断。

综上，除希望修复顶层`disabled`项外，增加逻辑判断`v-menu`的传入数据是否为`false`、`null`、`undefined`等，用以判断是否完全禁用菜单。
#### 3、分割线支持hidden或末端隐藏
分割线一旦配置了就只能一直显示，无法通过`hidden`选项动态显示隐藏，在显示效果上很突兀。希望分割线支持`hidden`。
`末端隐藏`是指，当分割线处于可显示菜单的最后时，自动隐藏。当然应该不是优先度高的功能，因为只要支持`hidden`选项即可间接实现

#### 0、文档错别字提醒
[https://kongfandong.cn/howdy/mouse-menu/readme](https://kongfandong.cn/howdy/mouse-menu/readme)中，  
````
配置
Props/指令Value (Objcet)
````
应为
````
配置
Props/指令Value (Object)
````

**Comment by leon-kfd** [comment]
感谢使用。
+ 第一点，接受建议，TODO。
+ 关于第二点，disabled参数应该能生效吧？我在自己项目能使用成功
具体参考此处：https://github.com/leon-kfd/Dashboard/blob/main/src/components/Layout.vue#L25
这个是自定义浏览器起始页项目，物料组件的右键菜单会根据当前是否锁定状态来判断是否启用，并没有你那个报错。
+ 第三点：接受建议， TODO。

**Comment by zheung** [comment]
#### 我的环境
````json
{
	"devDependencies": {
		"@howdyjs/mouse-menu": "^2.0.2",
		"@vitejs/plugin-vue": "^2.0.1",
		"vite": "^2.7.6",
		"vue": "^3.2.26"
	}
}
````
原来我的使用方式是object变量加入`disabled`函数的。
![image](https://user-images.githubusercontent.com/894004/147381969-6a2a4dcf-8d47-4bcd-849c-b9ca01b31749.png)
后来参照你提供的示例，改在html中以内联的方式测试，也会出现同样的提示。
![image](https://user-images.githubusercontent.com/894004/147381991-421e8fc6-272a-4606-b93a-fbbb2ee737f5.png)
所以应该与代码位置无关。即使`disabled`函数中加入`debugger`，也没有触发暂停

#### 尝试调试
关于第二条，粗略地尝试通过前端调试器定位一下
![image](https://user-images.githubusercontent.com/894004/147381621-91d968bf-7396-4b18-9ed3-6b8131e32639.png)
![image](https://user-images.githubusercontent.com/894004/147381608-01e0848a-272f-48f4-9489-f0207c08db67.png)

定位到CustomMouseMenu函数中，发现函数中`script`变量里的`props`值，似乎是定义v-menu传参的结构。里面有`params`呀`useLongPressInMobile`这样的顶级参数的定义，但是没有关于`disabled`的定义：
![image](https://user-images.githubusercontent.com/894004/147381871-06fa8138-0e63-4651-b61f-f1abb7311cd4.png)

翻查源码发现也是没有对应的`disabled`
https://github.com/leon-kfd/howdyjs/blob/6126e1d991a2f53a31ef5ee094ddf6471d556c93/packages/mouse-menu/mouse-menu.vue#L60-L102

由于没有仔细阅读调试源码，项目也不是TypeScript项目，所以并不能确实是这里导致的，仅供参考 : )

**Comment by leon-kfd** [comment]
不好意思哦，我现在才发现disabled只处理了兼容移动端的长按事件，我会有空尽快发布一版修复版本和有以上建议的版本。
在此之前，你可以参考以下来自行二次封装实现disabled功能。

https://github.com/leon-kfd/Dashboard/blob/main/src/plugins/mouse-menu.ts#L71

**Comment by leon-kfd** [comment]
@zheung 
以上功能已经实现发布，[@howdjs/mouse-menu@2.0.3](https://www.npmjs.com/package/@howdyjs/mouse-menu/v/2.0.3)
示例参考: [https://kongfandong.cn/howdy/mouse-menu/example7](https://kongfandong.cn/howdy/mouse-menu/example7)

**Comment by zheung** [comment]
> @zheung 以上功能已经实现发布，[@howdjs/mouse-menu@2.0.3](https://www.npmjs.com/package/@howdyjs/mouse-menu/v/2.0.3) 示例参考: https://kongfandong.cn/howdy/mouse-menu/example7

已用上，非常感谢
