### ISSUE TITLE
自定义右键菜单的ts提示  children  应该是可选的

### ISSUE THREAD

**Issue by ketao4869** [leon-kfd/howdyjs#13]
https://github.com/leon-kfd/howdyjs/blob/master/packages/mouse-menu/types.ts    

```js
export type MenuSetting = {
  fn?: MenuCallback;
  label?: string | MenuCallback<string>;
  tips?: string | MenuCallback<string>;
  hidden?: boolean | MenuCallback<boolean>;
  disabled?: boolean | MenuCallback<boolean>;
  icon?: string | MenuCallback<string>;
  line?: boolean;
  children?: MenuSetting[]; // 应该是可选的
  customClass?: string;
}
```

**Comment by ketao4869** [comment]
![image](https://user-images.githubusercontent.com/54937496/151329740-0627b4de-823b-4ede-8cdd-1e444030791d.png)

**Comment by ketao4869** [comment]
![image](https://user-images.githubusercontent.com/54937496/151329818-046096ce-f0ab-427e-97d0-ac1088165e2a.png)

不传 children:[]  就会警告，但是不影响运行

**Comment by leon-kfd** [comment]
对哦，子菜单直接也用了这个type，是个bug，我修复一下，感谢反馈

**Comment by leon-kfd** [comment]
Fixed, [@howdyjs/mouse-menu@2.0.4](https://www.npmjs.com/package/@howdyjs/mouse-menu/v/2.0.4)
