### ISSUE TITLE
怎么安装, 怎么全局注册指令, 都写下到readme前面会好点

### ISSUE THREAD

**Issue by a15218378694** [leon-kfd/howdyjs#14]
改怎么在ts项目下, 全局注册这些指令呢, 目前碰到了update报错

**Comment by leon-kfd** [comment]
提供指令的包，用app.use应该就可以全局注册，当前是什么报错，请列一下谢谢。

**Comment by a15218378694** [comment]
![image](https://user-images.githubusercontent.com/29919045/154885345-1dddd053-1f6a-4d9d-95d3-ee08124d8742.png)

**Comment by leon-kfd** [comment]
![image](https://user-images.githubusercontent.com/30256102/154891439-3f94554b-95e2-48d0-9d59-407ad8d6a074.png)
你那里应该是多了一层{}

**Comment by a15218378694** [comment]
还是报错
![image](https://user-images.githubusercontent.com/29919045/154898419-8540e3c5-2d86-415e-8953-fd54a1547f6b.png)
![image](https://user-images.githubusercontent.com/29919045/154898436-1214d67f-8299-4a6c-8b24-9f9d1d3c5862.png)

**Comment by leon-kfd** [comment]
`updated`那个包里默认没加，要用`as DirectiveHook`断言一下，可参考我发的截图。另右键菜单命令其实默认并不需要updated时更新。

> ![image](https://user-images.githubusercontent.com/30256102/154891439-3f94554b-95e2-48d0-9d59-407ad8d6a074.png) 你那里应该是多了一层{}

**Comment by a15218378694** [comment]
> `updated`那个包里默认没加，要用`as DirectiveHook`断言一下，可参考我发的截图。另右键菜单命令其实默认并不需要updated时更新。
> 
> > ![image](https://user-images.githubusercontent.com/30256102/154891439-3f94554b-95e2-48d0-9d59-407ad8d6a074.png) 你那里应该是多了一层{}

![image](https://user-images.githubusercontent.com/29919045/154900576-c95bfd78-6e16-4f57-82ec-881c86823b9c.png)
我改了之后代码报错, 全局注册不行, 局部可以

**Comment by leon-kfd** [comment]
`app.directive('mouse-menu', MouseMenuDirective)`
可能是app.directive你的命名错了。

**Comment by a15218378694** [comment]
> 

还是报错

**Comment by a15218378694** [comment]
方便的话还是希望可以解答下哈

**Comment by a15218378694** [comment]
> 简单全局注册Demo: https://codesandbox.io/s/reverent-smoke-or9egn?file=/src/App.vue

指令名不能用大驼峰的问题, 谢谢
