### ISSUE TITLE
element ui 里的table组件 怎么使用这个来自定义鼠标右键呢

### ISSUE THREAD

**Issue by luoyuchen** [leon-kfd/howdyjs#15]
element 是以列为单位的

**Comment by leon-kfd** [comment]
https://codepen.io/leon-kfd/pen/yLMKPOP?editors=0010
这个是为`ElementPlus`table组件添加右键菜单的实例，使用`CustomMouseMenu`

**Comment by luoyuchen** [comment]
感谢，正式我在找的。

**Comment by luoyuchen** [comment]
感谢，正是我在找的。完美解决
