### ISSUE TITLE
打开右键菜单后，滚动页面，右键菜单自动消失，怎么实现呢

### ISSUE THREAD

**Issue by yangyangxiange** [leon-kfd/howdyjs#16]

**Comment by leon-kfd** [comment]
你是用那种方式使用的？vue指令吗

**Comment by yangyangxiange** [comment]
嗯。对的，我现在用了一种方式是，监听滚动事件，滚动的时候把__menu__wrapper的display设置为none
这样也实现了，就是不知道有没有更好的方法。

**Comment by leon-kfd** [comment]
发布了一个@howdjs/mouse-menu@2.0.7的包，把MouseMenuCtx导出来了，可以直接用这个关闭。
参考[Example1](https://kongfandong.cn/howdy/mouse-menu/example1)

**Comment by yangyangxiange** [comment]
感谢感谢！
