### ISSUE TITLE
@howdyjs/mouse-menu的onOpen事件能否传递参数

### ISSUE THREAD

**Issue by Brioal** [leon-kfd/howdyjs#17]
感谢大佬的组件，非常好用，简单易懂，实际项目中用的时候遇到一点问题，如下：
在右键一个元素的时候，希望能在onOpen事件里面获取到元素携带的参数，大佬能否抽空实现一下，感激不尽

**Comment by leon-kfd** [comment]
- @howdyjs/mouse-menu@2.1.2

https://github.com/leon-kfd/howdyjs/commit/fecd83d8ca5ec3b514bbe39a00fee36b987532be
