### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by xiaoxian521** [leon-kfd/howdyjs#18]
作者，你好，反馈个问题。`tsc`检测报错 文件找不到，如下图

<img width="915" alt="image" src="https://github.com/leon-kfd/howdyjs/assets/44761321/27b1fdf6-125a-4d86-9df0-dbe03a547def">

**Comment by leon-kfd** [comment]
发布了[@howdyjs/mouse-menu@2.1.3](https://www.npmjs.com/package/@howdyjs/mouse-menu/v/2.1.3)

恢复了d.ts文件，但仍然没处理`.vue`，vue工程好像是用vue-tsc检测来着。或者tsconfig忽略这个包的检测。太久没维护这个了，有点操作忘了之前怎么设计了，抱歉。
