### ISSUE TITLE
@howdyjs/to-drag isAbsolute 和 adsorb 不能一起吗

### ISSUE THREAD

**Issue by uubyte** [leon-kfd/howdyjs#19]
@howdyjs/to-drag isAbsolute 和 adsorb 不能一起吗

**Comment by uubyte** [comment]
拖拽的时候会触发里面的click事件，没阻止，难受

**Comment by leon-kfd** [comment]
> 拖拽的时候会触发里面的click事件，没阻止，难受

你是想在进行了拖拽就不触发click，然后没拖拽过就照常触发click吗？

**Comment by uubyte** [comment]
<div v-super-drag="options">
   <div @click="handlexxxx">
       一拖拽就触发了handlexxxx，我下了源码，修复了，拖拽中不触发子级所有click事件，拖拽结束恢复可用！
   </div>
</div>
还是还有一点0.o   我想在isAbsolute下使用吸附 没办法办到，现在还隔着修，修不好

**Comment by uubyte** [comment]
一拖拽就触发了handleOk，我下了源码，修复了，拖拽中不触发子级所有click事件，拖拽结束恢复可用！
还是还有一点0.o 我想在isAbsolute下使用吸附 没办法办到，现在还隔着修，修不好！
![QQ截图20240822143643](https://github.com/user-attachments/assets/e21b21ad-b540-4e04-8564-91fc914d0405)

**Comment by uubyte** [comment]
> > 拖拽的时候会触发里面的点击事件，没阻止，难受
> 
> 你想在进行了拖拽不点击，然后拖拽没有触发就照常触发点击吗？

作者还在么

**Comment by leon-kfd** [comment]
![image](https://github.com/user-attachments/assets/f7cdaaf9-935d-4e55-8259-d26c3c30161a)
可以定义一个变量，然后在这个start和move回调里面判断是否经历过move，需要阻止click的时候判断一下再执行逻辑就行。

**Comment by uubyte** [comment]
![QQ截图20240822143959](https://github.com/user-attachments/assets/d8692660-03c2-41da-ae38-04a84aef9f39)
![微信截图_20240822144027](https://github.com/user-attachments/assets/fb5752aa-172a-4a7c-8421-46cee515e03c)
![微信截图_20240822144048](https://github.com/user-attachments/assets/05ece3b8-377e-4ada-b049-ac799b9b5ab3)
![微信截图_20240822144111](https://github.com/user-attachments/assets/146cd7bf-57db-47d8-8d4c-46c3e5a4d1a8)
![微信截图_20240822144120](https://github.com/user-attachments/assets/d4816c50-e1b8-4e4f-9c05-ba52867dd648)
我是这么解决的

**Comment by uubyte** [comment]
> ![图像](https://private-user-images.githubusercontent.com/30256102/360315208-f7cdaaf9-935d-4e55-8259-d26c3c30161a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMDkxOTksIm5iZiI6MTcyNDMwODg5OSwicGF0aCI6Ii8zMDI1NjEwMi8zNjAzMTUyMDgtZjdjZGFhZjktOTM1ZC00ZTU1LTgyNTktZDI2YzNjMzAxNjFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA2NDEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmOWEzZWYxNmJkYzY5NjQyMzQ1YzdiNDY5Y2Y5NTEzYTcyZGQ1YWRhY2JjMzQwZDcxMDE5YmVjNmM5Yjc0ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E5OsGPitMgkXzhX94Sz6IWWMZELFdIQty7HVBzm9SHI) 可以定义一个变量，然后在这个start和move回调里面判断是否经历过move，需要阻止点击的时候判断一下再执行逻辑就行。

尊敬的作者，那个绝对模式(isAbsolute)下，吸附要怎么做

**Comment by leon-kfd** [comment]
isAbsolute是后面加的，所以没实现，直接return了。要实现也是将屏幕尺寸判断改为父盒子尺寸判断应该就行

**Comment by uubyte** [comment]
> isAbsolute是后面加的，所以没实现，直接返回了。要实现也是将屏幕尺寸判断改为父屏幕尺寸判断就应该行

尊敬的作者 可以写个demo么 或者改一下

**Comment by leon-kfd** [comment]
@howdyjs/to-drag@2.1.4  在isAbsolute模式下支持吸附。

实例：https://codepen.io/leon-kfd/pen/PorRVWz

**Comment by uubyte** [comment]
> @howdyjs/to-drag@2.1.4 在isAbsolute模式下支持吸附。
> 
> 实例：https://codepen.io/leon-kfd/pen/PorRVWz

辛苦啦

**Comment by uubyte** [comment]
> @howdyjs/to-drag@2.1.4 在isAbsolute模式下支持吸附。
> 
> 实例：https://codepen.io/leon-kfd/pen/PorRVWz

辛苦啦

**Comment by uubyte** [comment]
> isAbsolute是后面加的，所以没实现，直接return了。要实现也是将屏幕尺寸判断改为父盒子尺寸判断应该就行

好像给不了默认位置

**Comment by uubyte** [comment]
> isAbsolute是后面加的，所以没实现，直接return了。要实现也是将屏幕尺寸判断改为父盒子尺寸判断应该就行

处于停止状态，点击时候会自动改变位置0.o

**Comment by uubyte** [comment]
> isAbsolute是后面加的，所以没实现，直接return了。要实现也是将屏幕尺寸判断改为父盒子尺寸判断应该就行

isAbsolute模式下 点着点着就跑容器外面去了

**Comment by uubyte** [comment]
![1](https://github.com/user-attachments/assets/9d0c10c2-62f1-4c13-80da-9678acfbf5cd)

**Comment by leon-kfd** [comment]
丢失了一个判断，https://github.com/leon-kfd/howdyjs/commit/b4c69859ae2ebdb080d33b8254ef226514e85728 看这个commit修复，晚点有空再发个包

**Comment by uubyte** [comment]
> 丢失了一个判断，[b4c6985](https://github.com/leon-kfd/howdyjs/commit/b4c69859ae2ebdb080d33b8254ef226514e85728) 看这个commit修复，晚点有空再发个包 @howdyjs/to-drag@2.1.5

要不先不忙着发包，加个初始化位置设置呗

**Comment by leon-kfd** [comment]
不是有个init的回调吗？而且你也可以直接设置dom的初始位置css

**Comment by uubyte** [comment]
> 不是有个init的回调吗？而且你也可以直接设置dom的初始位置css

好吧，只是感觉配置更好，那我直接操作dom吧 虽然不建议这样操作

**Comment by uubyte** [comment]
> 不是有个init的回调吗？而且你也可以直接设置dom的初始位置css

作者发个球球啥的好不 我截图给你看问题
