### ISSUE TITLE
@howdyjs/mouse-menu 二级菜单首次展示问题

### ISSUE THREAD

**Issue by chengbieSWL** [leon-kfd/howdyjs#20]
"@howdyjs/mouse-menu": "^2.1.3"
当菜单在浏览器最右侧弹出，鼠标首次滑入到有二级的位置，二级菜单会超出浏览器（在一级菜单右侧），再次滑入会正常展示（在一级菜单左侧），希望能优化一下
![image](https://github.com/user-attachments/assets/c3eff51d-c0e5-48da-abae-15379f8b8f7b)

**Comment by leon-kfd** [comment]
fix: 6124f3116638233d1ea4ca55d9620004322d3ae6

更新到`@howdyjs/mouse-menu@2.1.4`修复
