### ISSUE TITLE
设置了menuWitdh:150，二级列表的样式不生效

### ISSUE THREAD

**Issue by XuFeiYang521** [leon-kfd/howdyjs#21]
![image](https://github.com/user-attachments/assets/66e70ada-f1e5-482d-a0e6-f4523b1fdd67)

**Comment by XuFeiYang521** [comment]
父级设置了menuWidth:150， 但是二级菜单样式没有变

**Comment by leon-kfd** [comment]
506613ed1de67a99eba0e7c12e631d7d2dd59eab

更新`@howdyjs/mouse-menu@2.1.5` 
+ 优化: 子菜单允许设置menuWidth和图标
