### ISSUE TITLE
@howdyjs/mouse-menu在vue3 ts环境打包失败

### ISSUE THREAD

**Issue by racns** [leon-kfd/howdyjs#23]
@howdyjs/mouse-menu版本号2.1.6，在vue3 vite ts环境中使用npm run build打包打包失败，主要原因是@howdyjs/mouse-menu分包导入缺失mouse-menu.vue文件

![QQ_1729443353663](https://github.com/user-attachments/assets/4077082b-ad9d-4fd6-88ed-38ea495b6e9b)

**Comment by leon-kfd** [comment]
应该是TS工程配置识别不了.vue文件
可以试下加*.d.ts
```
declare module '*.vue' {
  import { App, defineComponent } from 'vue';
  const component: ReturnType<typeof defineComponent> & {
    install(app: App): void
  };
  export default component;
}
```

看一下你工程直接import其他.vue文件有没有报错提示

**Comment by racns** [comment]
![QQ_1729486790651](https://github.com/user-attachments/assets/dc609a76-a3e0-493b-b14b-f77a47a9f6bb)
修改后，npm run build打包通过了，但是到线上环境就开始报新的错误了
![QQ_1729486887692](https://github.com/user-attachments/assets/f483b732-0b43-4817-9c8c-7ae2bc272fdb)
![QQ_1729486905177](https://github.com/user-attachments/assets/6ba37b19-6d68-4458-ac92-b09c1de15818)

已自测，最小影响范围在注册全局组件的地方
![QQ_1729487001047](https://github.com/user-attachments/assets/84b6427f-1b77-47df-8bc1-b8414f0db674)
全局注册出现了该问题

**Comment by leon-kfd** [comment]
本地测试全局注册没发现问题

**Comment by leon-kfd** [comment]
https://github.com/leon-kfd/mouse-menu-test

+ npm i
+ npm run build
+ npm run preview

preview就是打包后环境预览 我这边正常

**Comment by racns** [comment]
找到问题了，是我做了编译分包处理的问题，打扰了，谢谢指导
