### ISSUE TITLE
build.js 一处疑问

### ISSUE THREAD

**Issue by wungjyan** [leon-kfd/howdyjs#9]
在 `script/build.js` 文件中，我红线划的这句里，`__dirname` 是不是应该改成 `dirName` ?

![image](https://user-images.githubusercontent.com/29590076/133362636-70b0c008-2827-4148-8e65-b8a03d33ea2d.png)

**Comment by leon-kfd** [comment]
看了下，这里的确是写错了，感谢指正，已修改
